/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthAttendanceRouteImport } from './routes/_auth/attendance'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthCustomersRouteImport } from './routes/_auth/customers'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthFilesRouteImport } from './routes/_auth/files'
import { Route as AuthInvoicesRouteImport } from './routes/_auth/invoices'
import { Route as AuthKanbanRouteImport } from './routes/_auth/kanban'
import { Route as AuthMessagesRouteImport } from './routes/_auth/messages'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthPayrollRouteImport } from './routes/_auth/payroll'
import { Route as AuthProductsRouteImport } from './routes/_auth/products'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthReportsRouteImport } from './routes/_auth/reports'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthTeamRouteImport } from './routes/_auth/team'
import { Route as AuthWorkspaceRouteImport } from './routes/_auth/workspace'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as AuthFinanceIndexRouteImport } from './routes/_auth/finance/index'
import { Route as AuthFinanceChartOfAccountsRouteImport } from './routes/_auth/finance/chart-of-accounts'
import { Route as AuthFinanceJournalEntriesRouteImport } from './routes/_auth/finance/journal-entries'
import { Route as AuthFinancePaymentsRouteImport } from './routes/_auth/finance/payments'
import { Route as AuthFinanceTransactionsRouteImport } from './routes/_auth/finance/transactions'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects/$projectId'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthReportsApAgingRouteImport } from './routes/_auth/reports/ap-aging'
import { Route as AuthReportsArAgingRouteImport } from './routes/_auth/reports/ar-aging'
import { Route as AuthReportsAttendanceReportRouteImport } from './routes/_auth/reports/attendance-report'
import { Route as AuthReportsBalanceSheetRouteImport } from './routes/_auth/reports/balance-sheet'
import { Route as AuthReportsCashFlowRouteImport } from './routes/_auth/reports/cash-flow'
import { Route as AuthReportsGeneralLedgerRouteImport } from './routes/_auth/reports/general-ledger'
import { Route as AuthReportsIncomeStatementRouteImport } from './routes/_auth/reports/income-statement'
import { Route as AuthReportsInventoryReportRouteImport } from './routes/_auth/reports/inventory-report'
import { Route as AuthReportsInvoiceSummaryRouteImport } from './routes/_auth/reports/invoice-summary'
import { Route as AuthReportsPayrollReportRouteImport } from './routes/_auth/reports/payroll-report'
import { Route as AuthReportsSalesReportRouteImport } from './routes/_auth/reports/sales-report'
import { Route as AuthReportsTrialBalanceRouteImport } from './routes/_auth/reports/trial-balance'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSettingsAccountRouteImport } from './routes/_auth/settings/account'
import { Route as AuthSettingsBillingRouteImport } from './routes/_auth/settings/billing'
import { Route as AuthSettingsConnectedAppsRouteImport } from './routes/_auth/settings/connected-apps'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth/settings/notifications'
import { Route as AuthSettingsPlansRouteImport } from './routes/_auth/settings/plans'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthFinanceTransactionsBillsRouteImport } from './routes/_auth/finance/transactions/bills'
import { Route as AuthFinanceTransactionsEquityRouteImport } from './routes/_auth/finance/transactions/equity'
import { Route as AuthFinanceTransactionsExpensesRouteImport } from './routes/_auth/finance/transactions/expenses'
import { Route as AuthFinanceTransactionsInvoicesRouteImport } from './routes/_auth/finance/transactions/invoices'
import { Route as AuthFinanceTransactionsKasbonRouteImport } from './routes/_auth/finance/transactions/kasbon'
import { Route as AuthFinanceTransactionsTransfersRouteImport } from './routes/_auth/finance/transactions/transfers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAttendanceRoute = AuthAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesRoute = AuthFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKanbanRoute = AuthKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesRoute = AuthMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPayrollRoute = AuthPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamRoute = AuthTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRoute,
} as any)
const AuthFinanceIndexRoute = AuthFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinanceChartOfAccountsRoute =
  AuthFinanceChartOfAccountsRouteImport.update({
    id: '/finance/chart-of-accounts',
    path: '/finance/chart-of-accounts',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFinanceJournalEntriesRoute =
  AuthFinanceJournalEntriesRouteImport.update({
    id: '/finance/journal-entries',
    path: '/finance/journal-entries',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthFinancePaymentsRoute = AuthFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinanceTransactionsRoute = AuthFinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProjectsRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AuthProjectsRoute,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthReportsApAgingRoute = AuthReportsApAgingRouteImport.update({
  id: '/ap-aging',
  path: '/ap-aging',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthReportsArAgingRoute = AuthReportsArAgingRouteImport.update({
  id: '/ar-aging',
  path: '/ar-aging',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthReportsAttendanceReportRoute =
  AuthReportsAttendanceReportRouteImport.update({
    id: '/attendance-report',
    path: '/attendance-report',
    getParentRoute: () => AuthReportsRoute,
  } as any)
const AuthReportsBalanceSheetRoute = AuthReportsBalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthReportsCashFlowRoute = AuthReportsCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthReportsGeneralLedgerRoute =
  AuthReportsGeneralLedgerRouteImport.update({
    id: '/general-ledger',
    path: '/general-ledger',
    getParentRoute: () => AuthReportsRoute,
  } as any)
const AuthReportsIncomeStatementRoute =
  AuthReportsIncomeStatementRouteImport.update({
    id: '/income-statement',
    path: '/income-statement',
    getParentRoute: () => AuthReportsRoute,
  } as any)
const AuthReportsInventoryReportRoute =
  AuthReportsInventoryReportRouteImport.update({
    id: '/inventory-report',
    path: '/inventory-report',
    getParentRoute: () => AuthReportsRoute,
  } as any)
const AuthReportsInvoiceSummaryRoute =
  AuthReportsInvoiceSummaryRouteImport.update({
    id: '/invoice-summary',
    path: '/invoice-summary',
    getParentRoute: () => AuthReportsRoute,
  } as any)
const AuthReportsPayrollReportRoute =
  AuthReportsPayrollReportRouteImport.update({
    id: '/payroll-report',
    path: '/payroll-report',
    getParentRoute: () => AuthReportsRoute,
  } as any)
const AuthReportsSalesReportRoute = AuthReportsSalesReportRouteImport.update({
  id: '/sales-report',
  path: '/sales-report',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthReportsTrialBalanceRoute = AuthReportsTrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => AuthReportsRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccountRoute = AuthSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsBillingRoute = AuthSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsConnectedAppsRoute =
  AuthSettingsConnectedAppsRouteImport.update({
    id: '/connected-apps',
    path: '/connected-apps',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsPlansRoute = AuthSettingsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthFinanceTransactionsBillsRoute =
  AuthFinanceTransactionsBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => AuthFinanceTransactionsRoute,
  } as any)
const AuthFinanceTransactionsEquityRoute =
  AuthFinanceTransactionsEquityRouteImport.update({
    id: '/equity',
    path: '/equity',
    getParentRoute: () => AuthFinanceTransactionsRoute,
  } as any)
const AuthFinanceTransactionsExpensesRoute =
  AuthFinanceTransactionsExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthFinanceTransactionsRoute,
  } as any)
const AuthFinanceTransactionsInvoicesRoute =
  AuthFinanceTransactionsInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthFinanceTransactionsRoute,
  } as any)
const AuthFinanceTransactionsKasbonRoute =
  AuthFinanceTransactionsKasbonRouteImport.update({
    id: '/kasbon',
    path: '/kasbon',
    getParentRoute: () => AuthFinanceTransactionsRoute,
  } as any)
const AuthFinanceTransactionsTransfersRoute =
  AuthFinanceTransactionsTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthFinanceTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/attendance': typeof AuthAttendanceRoute
  '/calendar': typeof AuthCalendarRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files': typeof AuthFilesRoute
  '/invoices': typeof AuthInvoicesRoute
  '/kanban': typeof AuthKanbanRoute
  '/messages': typeof AuthMessagesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/orders': typeof AuthOrdersRoute
  '/payroll': typeof AuthPayrollRoute
  '/products': typeof AuthProductsRoute
  '/profile': typeof AuthProfileRoute
  '/projects': typeof AuthProjectsRouteWithChildren
  '/reports': typeof AuthReportsRouteWithChildren
  '/settings': typeof AuthSettingsRouteWithChildren
  '/team': typeof AuthTeamRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/finance/chart-of-accounts': typeof AuthFinanceChartOfAccountsRoute
  '/finance/journal-entries': typeof AuthFinanceJournalEntriesRoute
  '/finance/payments': typeof AuthFinancePaymentsRoute
  '/finance/transactions': typeof AuthFinanceTransactionsRouteWithChildren
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/reports/ap-aging': typeof AuthReportsApAgingRoute
  '/reports/ar-aging': typeof AuthReportsArAgingRoute
  '/reports/attendance-report': typeof AuthReportsAttendanceReportRoute
  '/reports/balance-sheet': typeof AuthReportsBalanceSheetRoute
  '/reports/cash-flow': typeof AuthReportsCashFlowRoute
  '/reports/general-ledger': typeof AuthReportsGeneralLedgerRoute
  '/reports/income-statement': typeof AuthReportsIncomeStatementRoute
  '/reports/inventory-report': typeof AuthReportsInventoryReportRoute
  '/reports/invoice-summary': typeof AuthReportsInvoiceSummaryRoute
  '/reports/payroll-report': typeof AuthReportsPayrollReportRoute
  '/reports/sales-report': typeof AuthReportsSalesReportRoute
  '/reports/trial-balance': typeof AuthReportsTrialBalanceRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/connected-apps': typeof AuthSettingsConnectedAppsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/plans': typeof AuthSettingsPlansRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/finance/': typeof AuthFinanceIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/reports/': typeof AuthReportsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/finance/transactions/bills': typeof AuthFinanceTransactionsBillsRoute
  '/finance/transactions/equity': typeof AuthFinanceTransactionsEquityRoute
  '/finance/transactions/expenses': typeof AuthFinanceTransactionsExpensesRoute
  '/finance/transactions/invoices': typeof AuthFinanceTransactionsInvoicesRoute
  '/finance/transactions/kasbon': typeof AuthFinanceTransactionsKasbonRoute
  '/finance/transactions/transfers': typeof AuthFinanceTransactionsTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/attendance': typeof AuthAttendanceRoute
  '/calendar': typeof AuthCalendarRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files': typeof AuthFilesRoute
  '/invoices': typeof AuthInvoicesRoute
  '/kanban': typeof AuthKanbanRoute
  '/messages': typeof AuthMessagesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/orders': typeof AuthOrdersRoute
  '/payroll': typeof AuthPayrollRoute
  '/products': typeof AuthProductsRoute
  '/profile': typeof AuthProfileRoute
  '/team': typeof AuthTeamRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/finance/chart-of-accounts': typeof AuthFinanceChartOfAccountsRoute
  '/finance/journal-entries': typeof AuthFinanceJournalEntriesRoute
  '/finance/payments': typeof AuthFinancePaymentsRoute
  '/finance/transactions': typeof AuthFinanceTransactionsRouteWithChildren
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/reports/ap-aging': typeof AuthReportsApAgingRoute
  '/reports/ar-aging': typeof AuthReportsArAgingRoute
  '/reports/attendance-report': typeof AuthReportsAttendanceReportRoute
  '/reports/balance-sheet': typeof AuthReportsBalanceSheetRoute
  '/reports/cash-flow': typeof AuthReportsCashFlowRoute
  '/reports/general-ledger': typeof AuthReportsGeneralLedgerRoute
  '/reports/income-statement': typeof AuthReportsIncomeStatementRoute
  '/reports/inventory-report': typeof AuthReportsInventoryReportRoute
  '/reports/invoice-summary': typeof AuthReportsInvoiceSummaryRoute
  '/reports/payroll-report': typeof AuthReportsPayrollReportRoute
  '/reports/sales-report': typeof AuthReportsSalesReportRoute
  '/reports/trial-balance': typeof AuthReportsTrialBalanceRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/connected-apps': typeof AuthSettingsConnectedAppsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/plans': typeof AuthSettingsPlansRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/finance': typeof AuthFinanceIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/finance/transactions/bills': typeof AuthFinanceTransactionsBillsRoute
  '/finance/transactions/equity': typeof AuthFinanceTransactionsEquityRoute
  '/finance/transactions/expenses': typeof AuthFinanceTransactionsExpensesRoute
  '/finance/transactions/invoices': typeof AuthFinanceTransactionsInvoicesRoute
  '/finance/transactions/kasbon': typeof AuthFinanceTransactionsKasbonRoute
  '/finance/transactions/transfers': typeof AuthFinanceTransactionsTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/attendance': typeof AuthAttendanceRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/files': typeof AuthFilesRoute
  '/_auth/invoices': typeof AuthInvoicesRoute
  '/_auth/kanban': typeof AuthKanbanRoute
  '/_auth/messages': typeof AuthMessagesRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/payroll': typeof AuthPayrollRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/projects': typeof AuthProjectsRouteWithChildren
  '/_auth/reports': typeof AuthReportsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/team': typeof AuthTeamRoute
  '/_auth/workspace': typeof AuthWorkspaceRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/_auth/finance/chart-of-accounts': typeof AuthFinanceChartOfAccountsRoute
  '/_auth/finance/journal-entries': typeof AuthFinanceJournalEntriesRoute
  '/_auth/finance/payments': typeof AuthFinancePaymentsRoute
  '/_auth/finance/transactions': typeof AuthFinanceTransactionsRouteWithChildren
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/_auth/reports/ap-aging': typeof AuthReportsApAgingRoute
  '/_auth/reports/ar-aging': typeof AuthReportsArAgingRoute
  '/_auth/reports/attendance-report': typeof AuthReportsAttendanceReportRoute
  '/_auth/reports/balance-sheet': typeof AuthReportsBalanceSheetRoute
  '/_auth/reports/cash-flow': typeof AuthReportsCashFlowRoute
  '/_auth/reports/general-ledger': typeof AuthReportsGeneralLedgerRoute
  '/_auth/reports/income-statement': typeof AuthReportsIncomeStatementRoute
  '/_auth/reports/inventory-report': typeof AuthReportsInventoryReportRoute
  '/_auth/reports/invoice-summary': typeof AuthReportsInvoiceSummaryRoute
  '/_auth/reports/payroll-report': typeof AuthReportsPayrollReportRoute
  '/_auth/reports/sales-report': typeof AuthReportsSalesReportRoute
  '/_auth/reports/trial-balance': typeof AuthReportsTrialBalanceRoute
  '/_auth/settings/account': typeof AuthSettingsAccountRoute
  '/_auth/settings/billing': typeof AuthSettingsBillingRoute
  '/_auth/settings/connected-apps': typeof AuthSettingsConnectedAppsRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/plans': typeof AuthSettingsPlansRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/finance/': typeof AuthFinanceIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/finance/transactions/bills': typeof AuthFinanceTransactionsBillsRoute
  '/_auth/finance/transactions/equity': typeof AuthFinanceTransactionsEquityRoute
  '/_auth/finance/transactions/expenses': typeof AuthFinanceTransactionsExpensesRoute
  '/_auth/finance/transactions/invoices': typeof AuthFinanceTransactionsInvoicesRoute
  '/_auth/finance/transactions/kasbon': typeof AuthFinanceTransactionsKasbonRoute
  '/_auth/finance/transactions/transfers': typeof AuthFinanceTransactionsTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/files'
    | '/invoices'
    | '/kanban'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/finance/chart-of-accounts'
    | '/finance/journal-entries'
    | '/finance/payments'
    | '/finance/transactions'
    | '/projects/$projectId'
    | '/reports/ap-aging'
    | '/reports/ar-aging'
    | '/reports/attendance-report'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/general-ledger'
    | '/reports/income-statement'
    | '/reports/inventory-report'
    | '/reports/invoice-summary'
    | '/reports/payroll-report'
    | '/reports/sales-report'
    | '/reports/trial-balance'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/notifications'
    | '/settings/plans'
    | '/settings/profile'
    | '/finance/'
    | '/projects/'
    | '/reports/'
    | '/settings/'
    | '/finance/transactions/bills'
    | '/finance/transactions/equity'
    | '/finance/transactions/expenses'
    | '/finance/transactions/invoices'
    | '/finance/transactions/kasbon'
    | '/finance/transactions/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/files'
    | '/invoices'
    | '/kanban'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/team'
    | '/workspace'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/finance/chart-of-accounts'
    | '/finance/journal-entries'
    | '/finance/payments'
    | '/finance/transactions'
    | '/projects/$projectId'
    | '/reports/ap-aging'
    | '/reports/ar-aging'
    | '/reports/attendance-report'
    | '/reports/balance-sheet'
    | '/reports/cash-flow'
    | '/reports/general-ledger'
    | '/reports/income-statement'
    | '/reports/inventory-report'
    | '/reports/invoice-summary'
    | '/reports/payroll-report'
    | '/reports/sales-report'
    | '/reports/trial-balance'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/notifications'
    | '/settings/plans'
    | '/settings/profile'
    | '/finance'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/finance/transactions/bills'
    | '/finance/transactions/equity'
    | '/finance/transactions/expenses'
    | '/finance/transactions/invoices'
    | '/finance/transactions/kasbon'
    | '/finance/transactions/transfers'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/analytics'
    | '/_auth/attendance'
    | '/_auth/calendar'
    | '/_auth/customers'
    | '/_auth/dashboard'
    | '/_auth/files'
    | '/_auth/invoices'
    | '/_auth/kanban'
    | '/_auth/messages'
    | '/_auth/notifications'
    | '/_auth/orders'
    | '/_auth/payroll'
    | '/_auth/products'
    | '/_auth/profile'
    | '/_auth/projects'
    | '/_auth/reports'
    | '/_auth/settings'
    | '/_auth/team'
    | '/_auth/workspace'
    | '/_guest/forgot-password'
    | '/_guest/reset-password'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/_auth/finance/chart-of-accounts'
    | '/_auth/finance/journal-entries'
    | '/_auth/finance/payments'
    | '/_auth/finance/transactions'
    | '/_auth/projects/$projectId'
    | '/_auth/reports/ap-aging'
    | '/_auth/reports/ar-aging'
    | '/_auth/reports/attendance-report'
    | '/_auth/reports/balance-sheet'
    | '/_auth/reports/cash-flow'
    | '/_auth/reports/general-ledger'
    | '/_auth/reports/income-statement'
    | '/_auth/reports/inventory-report'
    | '/_auth/reports/invoice-summary'
    | '/_auth/reports/payroll-report'
    | '/_auth/reports/sales-report'
    | '/_auth/reports/trial-balance'
    | '/_auth/settings/account'
    | '/_auth/settings/billing'
    | '/_auth/settings/connected-apps'
    | '/_auth/settings/notifications'
    | '/_auth/settings/plans'
    | '/_auth/settings/profile'
    | '/_auth/finance/'
    | '/_auth/projects/'
    | '/_auth/reports/'
    | '/_auth/settings/'
    | '/_auth/finance/transactions/bills'
    | '/_auth/finance/transactions/equity'
    | '/_auth/finance/transactions/expenses'
    | '/_auth/finance/transactions/invoices'
    | '/_auth/finance/transactions/kasbon'
    | '/_auth/finance/transactions/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/attendance': {
      id: '/_auth/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthAttendanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/files': {
      id: '/_auth/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthFilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban': {
      id: '/_auth/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthKanbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages': {
      id: '/_auth/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthMessagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payroll': {
      id: '/_auth/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthPayrollRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/team': {
      id: '/_auth/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspace': {
      id: '/_auth/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/finance/': {
      id: '/_auth/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthFinanceIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/finance/chart-of-accounts': {
      id: '/_auth/finance/chart-of-accounts'
      path: '/finance/chart-of-accounts'
      fullPath: '/finance/chart-of-accounts'
      preLoaderRoute: typeof AuthFinanceChartOfAccountsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/finance/journal-entries': {
      id: '/_auth/finance/journal-entries'
      path: '/finance/journal-entries'
      fullPath: '/finance/journal-entries'
      preLoaderRoute: typeof AuthFinanceJournalEntriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/finance/payments': {
      id: '/_auth/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AuthFinancePaymentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/finance/transactions': {
      id: '/_auth/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthFinanceTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/ap-aging': {
      id: '/_auth/reports/ap-aging'
      path: '/ap-aging'
      fullPath: '/reports/ap-aging'
      preLoaderRoute: typeof AuthReportsApAgingRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/ar-aging': {
      id: '/_auth/reports/ar-aging'
      path: '/ar-aging'
      fullPath: '/reports/ar-aging'
      preLoaderRoute: typeof AuthReportsArAgingRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/attendance-report': {
      id: '/_auth/reports/attendance-report'
      path: '/attendance-report'
      fullPath: '/reports/attendance-report'
      preLoaderRoute: typeof AuthReportsAttendanceReportRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/balance-sheet': {
      id: '/_auth/reports/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AuthReportsBalanceSheetRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/cash-flow': {
      id: '/_auth/reports/cash-flow'
      path: '/cash-flow'
      fullPath: '/reports/cash-flow'
      preLoaderRoute: typeof AuthReportsCashFlowRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/general-ledger': {
      id: '/_auth/reports/general-ledger'
      path: '/general-ledger'
      fullPath: '/reports/general-ledger'
      preLoaderRoute: typeof AuthReportsGeneralLedgerRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/income-statement': {
      id: '/_auth/reports/income-statement'
      path: '/income-statement'
      fullPath: '/reports/income-statement'
      preLoaderRoute: typeof AuthReportsIncomeStatementRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/inventory-report': {
      id: '/_auth/reports/inventory-report'
      path: '/inventory-report'
      fullPath: '/reports/inventory-report'
      preLoaderRoute: typeof AuthReportsInventoryReportRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/invoice-summary': {
      id: '/_auth/reports/invoice-summary'
      path: '/invoice-summary'
      fullPath: '/reports/invoice-summary'
      preLoaderRoute: typeof AuthReportsInvoiceSummaryRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/payroll-report': {
      id: '/_auth/reports/payroll-report'
      path: '/payroll-report'
      fullPath: '/reports/payroll-report'
      preLoaderRoute: typeof AuthReportsPayrollReportRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/sales-report': {
      id: '/_auth/reports/sales-report'
      path: '/sales-report'
      fullPath: '/reports/sales-report'
      preLoaderRoute: typeof AuthReportsSalesReportRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/reports/trial-balance': {
      id: '/_auth/reports/trial-balance'
      path: '/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AuthReportsTrialBalanceRouteImport
      parentRoute: typeof AuthReportsRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/billing': {
      id: '/_auth/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthSettingsBillingRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/connected-apps': {
      id: '/_auth/settings/connected-apps'
      path: '/connected-apps'
      fullPath: '/settings/connected-apps'
      preLoaderRoute: typeof AuthSettingsConnectedAppsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/plans': {
      id: '/_auth/settings/plans'
      path: '/plans'
      fullPath: '/settings/plans'
      preLoaderRoute: typeof AuthSettingsPlansRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/finance/transactions/bills': {
      id: '/_auth/finance/transactions/bills'
      path: '/bills'
      fullPath: '/finance/transactions/bills'
      preLoaderRoute: typeof AuthFinanceTransactionsBillsRouteImport
      parentRoute: typeof AuthFinanceTransactionsRoute
    }
    '/_auth/finance/transactions/equity': {
      id: '/_auth/finance/transactions/equity'
      path: '/equity'
      fullPath: '/finance/transactions/equity'
      preLoaderRoute: typeof AuthFinanceTransactionsEquityRouteImport
      parentRoute: typeof AuthFinanceTransactionsRoute
    }
    '/_auth/finance/transactions/expenses': {
      id: '/_auth/finance/transactions/expenses'
      path: '/expenses'
      fullPath: '/finance/transactions/expenses'
      preLoaderRoute: typeof AuthFinanceTransactionsExpensesRouteImport
      parentRoute: typeof AuthFinanceTransactionsRoute
    }
    '/_auth/finance/transactions/invoices': {
      id: '/_auth/finance/transactions/invoices'
      path: '/invoices'
      fullPath: '/finance/transactions/invoices'
      preLoaderRoute: typeof AuthFinanceTransactionsInvoicesRouteImport
      parentRoute: typeof AuthFinanceTransactionsRoute
    }
    '/_auth/finance/transactions/kasbon': {
      id: '/_auth/finance/transactions/kasbon'
      path: '/kasbon'
      fullPath: '/finance/transactions/kasbon'
      preLoaderRoute: typeof AuthFinanceTransactionsKasbonRouteImport
      parentRoute: typeof AuthFinanceTransactionsRoute
    }
    '/_auth/finance/transactions/transfers': {
      id: '/_auth/finance/transactions/transfers'
      path: '/transfers'
      fullPath: '/finance/transactions/transfers'
      preLoaderRoute: typeof AuthFinanceTransactionsTransfersRouteImport
      parentRoute: typeof AuthFinanceTransactionsRoute
    }
  }
}

interface AuthProjectsRouteChildren {
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
}

const AuthProjectsRouteChildren: AuthProjectsRouteChildren = {
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
}

const AuthProjectsRouteWithChildren = AuthProjectsRoute._addFileChildren(
  AuthProjectsRouteChildren,
)

interface AuthReportsRouteChildren {
  AuthReportsApAgingRoute: typeof AuthReportsApAgingRoute
  AuthReportsArAgingRoute: typeof AuthReportsArAgingRoute
  AuthReportsAttendanceReportRoute: typeof AuthReportsAttendanceReportRoute
  AuthReportsBalanceSheetRoute: typeof AuthReportsBalanceSheetRoute
  AuthReportsCashFlowRoute: typeof AuthReportsCashFlowRoute
  AuthReportsGeneralLedgerRoute: typeof AuthReportsGeneralLedgerRoute
  AuthReportsIncomeStatementRoute: typeof AuthReportsIncomeStatementRoute
  AuthReportsInventoryReportRoute: typeof AuthReportsInventoryReportRoute
  AuthReportsInvoiceSummaryRoute: typeof AuthReportsInvoiceSummaryRoute
  AuthReportsPayrollReportRoute: typeof AuthReportsPayrollReportRoute
  AuthReportsSalesReportRoute: typeof AuthReportsSalesReportRoute
  AuthReportsTrialBalanceRoute: typeof AuthReportsTrialBalanceRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
}

const AuthReportsRouteChildren: AuthReportsRouteChildren = {
  AuthReportsApAgingRoute: AuthReportsApAgingRoute,
  AuthReportsArAgingRoute: AuthReportsArAgingRoute,
  AuthReportsAttendanceReportRoute: AuthReportsAttendanceReportRoute,
  AuthReportsBalanceSheetRoute: AuthReportsBalanceSheetRoute,
  AuthReportsCashFlowRoute: AuthReportsCashFlowRoute,
  AuthReportsGeneralLedgerRoute: AuthReportsGeneralLedgerRoute,
  AuthReportsIncomeStatementRoute: AuthReportsIncomeStatementRoute,
  AuthReportsInventoryReportRoute: AuthReportsInventoryReportRoute,
  AuthReportsInvoiceSummaryRoute: AuthReportsInvoiceSummaryRoute,
  AuthReportsPayrollReportRoute: AuthReportsPayrollReportRoute,
  AuthReportsSalesReportRoute: AuthReportsSalesReportRoute,
  AuthReportsTrialBalanceRoute: AuthReportsTrialBalanceRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
}

const AuthReportsRouteWithChildren = AuthReportsRoute._addFileChildren(
  AuthReportsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsAccountRoute: typeof AuthSettingsAccountRoute
  AuthSettingsBillingRoute: typeof AuthSettingsBillingRoute
  AuthSettingsConnectedAppsRoute: typeof AuthSettingsConnectedAppsRoute
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsPlansRoute: typeof AuthSettingsPlansRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAccountRoute: AuthSettingsAccountRoute,
  AuthSettingsBillingRoute: AuthSettingsBillingRoute,
  AuthSettingsConnectedAppsRoute: AuthSettingsConnectedAppsRoute,
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsPlansRoute: AuthSettingsPlansRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthFinanceTransactionsRouteChildren {
  AuthFinanceTransactionsBillsRoute: typeof AuthFinanceTransactionsBillsRoute
  AuthFinanceTransactionsEquityRoute: typeof AuthFinanceTransactionsEquityRoute
  AuthFinanceTransactionsExpensesRoute: typeof AuthFinanceTransactionsExpensesRoute
  AuthFinanceTransactionsInvoicesRoute: typeof AuthFinanceTransactionsInvoicesRoute
  AuthFinanceTransactionsKasbonRoute: typeof AuthFinanceTransactionsKasbonRoute
  AuthFinanceTransactionsTransfersRoute: typeof AuthFinanceTransactionsTransfersRoute
}

const AuthFinanceTransactionsRouteChildren: AuthFinanceTransactionsRouteChildren =
  {
    AuthFinanceTransactionsBillsRoute: AuthFinanceTransactionsBillsRoute,
    AuthFinanceTransactionsEquityRoute: AuthFinanceTransactionsEquityRoute,
    AuthFinanceTransactionsExpensesRoute: AuthFinanceTransactionsExpensesRoute,
    AuthFinanceTransactionsInvoicesRoute: AuthFinanceTransactionsInvoicesRoute,
    AuthFinanceTransactionsKasbonRoute: AuthFinanceTransactionsKasbonRoute,
    AuthFinanceTransactionsTransfersRoute:
      AuthFinanceTransactionsTransfersRoute,
  }

const AuthFinanceTransactionsRouteWithChildren =
  AuthFinanceTransactionsRoute._addFileChildren(
    AuthFinanceTransactionsRouteChildren,
  )

interface AuthRouteChildren {
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthAttendanceRoute: typeof AuthAttendanceRoute
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthFilesRoute: typeof AuthFilesRoute
  AuthInvoicesRoute: typeof AuthInvoicesRoute
  AuthKanbanRoute: typeof AuthKanbanRoute
  AuthMessagesRoute: typeof AuthMessagesRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthPayrollRoute: typeof AuthPayrollRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthProjectsRoute: typeof AuthProjectsRouteWithChildren
  AuthReportsRoute: typeof AuthReportsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthTeamRoute: typeof AuthTeamRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
  AuthFinanceChartOfAccountsRoute: typeof AuthFinanceChartOfAccountsRoute
  AuthFinanceJournalEntriesRoute: typeof AuthFinanceJournalEntriesRoute
  AuthFinancePaymentsRoute: typeof AuthFinancePaymentsRoute
  AuthFinanceTransactionsRoute: typeof AuthFinanceTransactionsRouteWithChildren
  AuthFinanceIndexRoute: typeof AuthFinanceIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthAttendanceRoute: AuthAttendanceRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthCustomersRoute: AuthCustomersRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthFilesRoute: AuthFilesRoute,
  AuthInvoicesRoute: AuthInvoicesRoute,
  AuthKanbanRoute: AuthKanbanRoute,
  AuthMessagesRoute: AuthMessagesRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthPayrollRoute: AuthPayrollRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthProjectsRoute: AuthProjectsRouteWithChildren,
  AuthReportsRoute: AuthReportsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthTeamRoute: AuthTeamRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
  AuthFinanceChartOfAccountsRoute: AuthFinanceChartOfAccountsRoute,
  AuthFinanceJournalEntriesRoute: AuthFinanceJournalEntriesRoute,
  AuthFinancePaymentsRoute: AuthFinancePaymentsRoute,
  AuthFinanceTransactionsRoute: AuthFinanceTransactionsRouteWithChildren,
  AuthFinanceIndexRoute: AuthFinanceIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
