/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthAttendanceRouteImport } from './routes/_auth/attendance'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthCustomersRouteImport } from './routes/_auth/customers'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthFilesRouteImport } from './routes/_auth/files'
import { Route as AuthInvoicesRouteImport } from './routes/_auth/invoices'
import { Route as AuthKanbanRouteImport } from './routes/_auth/kanban'
import { Route as AuthMessagesRouteImport } from './routes/_auth/messages'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthPayrollRouteImport } from './routes/_auth/payroll'
import { Route as AuthProductsRouteImport } from './routes/_auth/products'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthTeamRouteImport } from './routes/_auth/team'
import { Route as AuthWorkspaceRouteImport } from './routes/_auth/workspace'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthProjectsProjectIdRouteImport } from './routes/_auth/projects/$projectId'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSettingsAccountRouteImport } from './routes/_auth/settings/account'
import { Route as AuthSettingsBillingRouteImport } from './routes/_auth/settings/billing'
import { Route as AuthSettingsConnectedAppsRouteImport } from './routes/_auth/settings/connected-apps'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth/settings/notifications'
import { Route as AuthSettingsPlansRouteImport } from './routes/_auth/settings/plans'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAttendanceRoute = AuthAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesRoute = AuthFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKanbanRoute = AuthKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesRoute = AuthMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPayrollRoute = AuthPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamRoute = AuthTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProjectsRoute,
} as any)
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AuthProjectsRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccountRoute = AuthSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsBillingRoute = AuthSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsConnectedAppsRoute =
  AuthSettingsConnectedAppsRouteImport.update({
    id: '/connected-apps',
    path: '/connected-apps',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthSettingsPlansRoute = AuthSettingsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/attendance': typeof AuthAttendanceRoute
  '/calendar': typeof AuthCalendarRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files': typeof AuthFilesRoute
  '/invoices': typeof AuthInvoicesRoute
  '/kanban': typeof AuthKanbanRoute
  '/messages': typeof AuthMessagesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/orders': typeof AuthOrdersRoute
  '/payroll': typeof AuthPayrollRoute
  '/products': typeof AuthProductsRoute
  '/profile': typeof AuthProfileRoute
  '/projects': typeof AuthProjectsRouteWithChildren
  '/settings': typeof AuthSettingsRouteWithChildren
  '/team': typeof AuthTeamRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/connected-apps': typeof AuthSettingsConnectedAppsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/plans': typeof AuthSettingsPlansRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/projects/': typeof AuthProjectsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/attendance': typeof AuthAttendanceRoute
  '/calendar': typeof AuthCalendarRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files': typeof AuthFilesRoute
  '/invoices': typeof AuthInvoicesRoute
  '/kanban': typeof AuthKanbanRoute
  '/messages': typeof AuthMessagesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/orders': typeof AuthOrdersRoute
  '/payroll': typeof AuthPayrollRoute
  '/products': typeof AuthProductsRoute
  '/profile': typeof AuthProfileRoute
  '/team': typeof AuthTeamRoute
  '/workspace': typeof AuthWorkspaceRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/settings/account': typeof AuthSettingsAccountRoute
  '/settings/billing': typeof AuthSettingsBillingRoute
  '/settings/connected-apps': typeof AuthSettingsConnectedAppsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/plans': typeof AuthSettingsPlansRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/projects': typeof AuthProjectsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/attendance': typeof AuthAttendanceRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/files': typeof AuthFilesRoute
  '/_auth/invoices': typeof AuthInvoicesRoute
  '/_auth/kanban': typeof AuthKanbanRoute
  '/_auth/messages': typeof AuthMessagesRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/payroll': typeof AuthPayrollRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/projects': typeof AuthProjectsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/team': typeof AuthTeamRoute
  '/_auth/workspace': typeof AuthWorkspaceRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/_auth/projects/$projectId': typeof AuthProjectsProjectIdRoute
  '/_auth/settings/account': typeof AuthSettingsAccountRoute
  '/_auth/settings/billing': typeof AuthSettingsBillingRoute
  '/_auth/settings/connected-apps': typeof AuthSettingsConnectedAppsRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/plans': typeof AuthSettingsPlansRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/files'
    | '/invoices'
    | '/kanban'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/team'
    | '/workspace'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/notifications'
    | '/settings/plans'
    | '/settings/profile'
    | '/projects/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/files'
    | '/invoices'
    | '/kanban'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/team'
    | '/workspace'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/connected-apps'
    | '/settings/notifications'
    | '/settings/plans'
    | '/settings/profile'
    | '/projects'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/analytics'
    | '/_auth/attendance'
    | '/_auth/calendar'
    | '/_auth/customers'
    | '/_auth/dashboard'
    | '/_auth/files'
    | '/_auth/invoices'
    | '/_auth/kanban'
    | '/_auth/messages'
    | '/_auth/notifications'
    | '/_auth/orders'
    | '/_auth/payroll'
    | '/_auth/products'
    | '/_auth/profile'
    | '/_auth/projects'
    | '/_auth/settings'
    | '/_auth/team'
    | '/_auth/workspace'
    | '/_guest/forgot-password'
    | '/_guest/reset-password'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/_auth/projects/$projectId'
    | '/_auth/settings/account'
    | '/_auth/settings/billing'
    | '/_auth/settings/connected-apps'
    | '/_auth/settings/notifications'
    | '/_auth/settings/plans'
    | '/_auth/settings/profile'
    | '/_auth/projects/'
    | '/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/attendance': {
      id: '/_auth/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthAttendanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/files': {
      id: '/_auth/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthFilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban': {
      id: '/_auth/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthKanbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages': {
      id: '/_auth/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthMessagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payroll': {
      id: '/_auth/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthPayrollRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/team': {
      id: '/_auth/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspace': {
      id: '/_auth/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/projects/$projectId': {
      id: '/_auth/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport
      parentRoute: typeof AuthProjectsRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/account': {
      id: '/_auth/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthSettingsAccountRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/billing': {
      id: '/_auth/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthSettingsBillingRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/connected-apps': {
      id: '/_auth/settings/connected-apps'
      path: '/connected-apps'
      fullPath: '/settings/connected-apps'
      preLoaderRoute: typeof AuthSettingsConnectedAppsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/plans': {
      id: '/_auth/settings/plans'
      path: '/plans'
      fullPath: '/settings/plans'
      preLoaderRoute: typeof AuthSettingsPlansRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
  }
}

interface AuthProjectsRouteChildren {
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
}

const AuthProjectsRouteChildren: AuthProjectsRouteChildren = {
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
}

const AuthProjectsRouteWithChildren = AuthProjectsRoute._addFileChildren(
  AuthProjectsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsAccountRoute: typeof AuthSettingsAccountRoute
  AuthSettingsBillingRoute: typeof AuthSettingsBillingRoute
  AuthSettingsConnectedAppsRoute: typeof AuthSettingsConnectedAppsRoute
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsPlansRoute: typeof AuthSettingsPlansRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAccountRoute: AuthSettingsAccountRoute,
  AuthSettingsBillingRoute: AuthSettingsBillingRoute,
  AuthSettingsConnectedAppsRoute: AuthSettingsConnectedAppsRoute,
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsPlansRoute: AuthSettingsPlansRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthRouteChildren {
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthAttendanceRoute: typeof AuthAttendanceRoute
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthFilesRoute: typeof AuthFilesRoute
  AuthInvoicesRoute: typeof AuthInvoicesRoute
  AuthKanbanRoute: typeof AuthKanbanRoute
  AuthMessagesRoute: typeof AuthMessagesRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthPayrollRoute: typeof AuthPayrollRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthProjectsRoute: typeof AuthProjectsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthTeamRoute: typeof AuthTeamRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthAttendanceRoute: AuthAttendanceRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthCustomersRoute: AuthCustomersRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthFilesRoute: AuthFilesRoute,
  AuthInvoicesRoute: AuthInvoicesRoute,
  AuthKanbanRoute: AuthKanbanRoute,
  AuthMessagesRoute: AuthMessagesRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthPayrollRoute: AuthPayrollRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthProjectsRoute: AuthProjectsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthTeamRoute: AuthTeamRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
