/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthAnalyticsRouteImport } from './routes/_auth/analytics'
import { Route as AuthCalendarRouteImport } from './routes/_auth/calendar'
import { Route as AuthCustomersRouteImport } from './routes/_auth/customers'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthFilesRouteImport } from './routes/_auth/files'
import { Route as AuthInvoicesRouteImport } from './routes/_auth/invoices'
import { Route as AuthKanbanRouteImport } from './routes/_auth/kanban'
import { Route as AuthMessagesRouteImport } from './routes/_auth/messages'
import { Route as AuthNotificationsRouteImport } from './routes/_auth/notifications'
import { Route as AuthOrdersRouteImport } from './routes/_auth/orders'
import { Route as AuthProductsRouteImport } from './routes/_auth/products'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthTeamRouteImport } from './routes/_auth/team'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnalyticsRoute = AuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCalendarRoute = AuthCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCustomersRoute = AuthCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFilesRoute = AuthFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvoicesRoute = AuthInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKanbanRoute = AuthKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessagesRoute = AuthMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNotificationsRoute = AuthNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTeamRoute = AuthTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/calendar': typeof AuthCalendarRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files': typeof AuthFilesRoute
  '/invoices': typeof AuthInvoicesRoute
  '/kanban': typeof AuthKanbanRoute
  '/messages': typeof AuthMessagesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/orders': typeof AuthOrdersRoute
  '/products': typeof AuthProductsRoute
  '/settings': typeof AuthSettingsRoute
  '/team': typeof AuthTeamRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/calendar': typeof AuthCalendarRoute
  '/customers': typeof AuthCustomersRoute
  '/dashboard': typeof AuthDashboardRoute
  '/files': typeof AuthFilesRoute
  '/invoices': typeof AuthInvoicesRoute
  '/kanban': typeof AuthKanbanRoute
  '/messages': typeof AuthMessagesRoute
  '/notifications': typeof AuthNotificationsRoute
  '/orders': typeof AuthOrdersRoute
  '/products': typeof AuthProductsRoute
  '/settings': typeof AuthSettingsRoute
  '/team': typeof AuthTeamRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/calendar': typeof AuthCalendarRoute
  '/_auth/customers': typeof AuthCustomersRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/files': typeof AuthFilesRoute
  '/_auth/invoices': typeof AuthInvoicesRoute
  '/_auth/kanban': typeof AuthKanbanRoute
  '/_auth/messages': typeof AuthMessagesRoute
  '/_auth/notifications': typeof AuthNotificationsRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/team': typeof AuthTeamRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/files'
    | '/invoices'
    | '/kanban'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/settings'
    | '/team'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/files'
    | '/invoices'
    | '/kanban'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/products'
    | '/settings'
    | '/team'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/analytics'
    | '/_auth/calendar'
    | '/_auth/customers'
    | '/_auth/dashboard'
    | '/_auth/files'
    | '/_auth/invoices'
    | '/_auth/kanban'
    | '/_auth/messages'
    | '/_auth/notifications'
    | '/_auth/orders'
    | '/_auth/products'
    | '/_auth/settings'
    | '/_auth/team'
    | '/_guest/forgot-password'
    | '/_guest/reset-password'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/calendar': {
      id: '/_auth/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/customers': {
      id: '/_auth/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthCustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/files': {
      id: '/_auth/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthFilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kanban': {
      id: '/_auth/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthKanbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/messages': {
      id: '/_auth/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthMessagesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/notifications': {
      id: '/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthNotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/team': {
      id: '/_auth/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthCalendarRoute: typeof AuthCalendarRoute
  AuthCustomersRoute: typeof AuthCustomersRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthFilesRoute: typeof AuthFilesRoute
  AuthInvoicesRoute: typeof AuthInvoicesRoute
  AuthKanbanRoute: typeof AuthKanbanRoute
  AuthMessagesRoute: typeof AuthMessagesRoute
  AuthNotificationsRoute: typeof AuthNotificationsRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthTeamRoute: typeof AuthTeamRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthCalendarRoute: AuthCalendarRoute,
  AuthCustomersRoute: AuthCustomersRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthFilesRoute: AuthFilesRoute,
  AuthInvoicesRoute: AuthInvoicesRoute,
  AuthKanbanRoute: AuthKanbanRoute,
  AuthMessagesRoute: AuthMessagesRoute,
  AuthNotificationsRoute: AuthNotificationsRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthTeamRoute: AuthTeamRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
